steps:
  # 1. Build the Streamlit application Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'Datascience/ML/04_StreamlitGCPDeployment' # <--- Sets the working directory (WD)
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/mybigmartprediction/streamlit-app-repo/streamlit-app:latest'
      - '.' # <--- Context: Use the current working directory (which is now the application folder)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/mybigmartprediction/streamlit-app-repo/streamlit-app:latest'
images:
  - 'us-central1-docker.pkg.dev/mybigmartprediction/streamlit-app-repo/streamlit-app:latest'
options:
  logging: CLOUD_LOGGING_ONLY
